In [85]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', 105)
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [86]:
train = pd.read_csv('Train.csv', header=0, index_col = 'Client ID')
train['Client Retention Flag'] = label.fit_transform(train['Client Retention Flag'])
test = pd.read_csv('Test.csv', header=0, index_col = 'Client ID')
y = train[train.columns[-1]]
train.drop(columns=['Client Retention Flag'], inplace=True)
train.shape

(8766, 104)

In [87]:
train_test = pd.merge(train, test, how='outer', on=list(train.columns), left_index=True, right_index=True)

In [88]:
data = [train_test, train, test]
for i in data:
    act = 1
    month = 11
    for col in i.columns[8:]:
        i.rename(columns={col: 'Activity '+ str(act)+ ' Time Period '+ str(month)}, inplace=True)
        if month == 0:
            month = 12
            act += 1
        month -= 1
    i.rename(columns = {'Flag 1':'No. of Years', 'Flag 2':'Service Category', 'Flag 3':'Eligibility for Inquiries', 'Flag 5':'Region Category', 'Flag 6':'Industry'}, inplace=True)

In [89]:
nunique = train_test.nunique()
r = train.nunique()
s = test.nunique()
o = pd.DataFrame(np.vstack((nunique, r, s)).T, index = train.columns)

In [90]:
for dataset in data:
    i = 1
    while i<9:
        dataset['Activity'+ str(i)] = np.sum(train[train.columns[(i-1)*12+8: i*12+8]], axis=1)
        i += 1

In [ ]:
'''train_y = train.copy()
train_y['y'] = y'''

In [92]:
activity_cols = ['Activity5', 'Activity6', 'Activity7']
train_test['least_1s'] = [1 if np.all(train_test.loc[index, activity_cols] > 0) else 0 for index in train_test.index]
train_test['sum>2'] = [1 if np.sum(train_test.loc[index, activity_cols], axis=0) > 2 else 0 for index in train_test.index]

activity_cols = ['Activity5', 'Activity6', 'Activity7', 'Activity8']
train_test['all_0s'] = [1 if np.all(train_test.loc[index, activity_cols].isin([0])) else 0 for index in train_test.index]

In [138]:
train['Eligibility for Inquiries'] = train['Eligibility for Inquiries'].str.replace('C', 'Yes')
train['Eligibility for Inquiries'] = label.fit_transform(train['Eligibility for Inquiries'])
train['No. of Years'] = label.fit_transform(train['No. of Years'])
train.tail()

Company ID Client Contract Starting Month  No. of Years  \
Client ID                                                              
10004522518     6292232                            Sep             1   
10004522519     6295090                            Sep             0   
10004522520     6292206                            Sep             1   
10004522521     6292565                            Sep             1   
10004522522     6293420                            Sep             0   

             Service Category  Eligibility for Inquiries  Region Category  \
Client ID                                                                   
10004522518                 2                          1                3   
10004522519                 2                          0                8   
10004522520                 2                          0                8   
10004522521                 6                          0               14   
10004522522                 2                          0                3   

                           Industry  Activity 1 Time Period 11  \
Client ID                                                        
10004522518               Education                         50   
10004522519              Government                          0   
10004522520           Manufacturing                          0   
10004522521  Banking, Finance & Ins                          0   
10004522522               Education                          0   

             Activity 1 Time Period 10  Activity 1 Time Period 9  \
Client ID                                                          
10004522518                         32                        16   
10004522519                          0                         0   
10004522520                          4                         2   
10004522521                          0                         0   
10004522522                          4                         0   

             Activity 1 Time Period 8  Activity 1 Time Period 7  \
Client ID                                                         
10004522518                        36                        38   
10004522519                         4                         0   
10004522520                         2                         0   
10004522521                         0                         0   
10004522522                         2                         0   

             Activity 1 Time Period 6  Activity 1 Time Period 5  \
Client ID                                                         
10004522518                        42                        34   
10004522519                         2                         0   
10004522520                         3                         2   
10004522521                         0                         0   
10004522522                         0                         0   

             Activity 1 Time Period 4  Activity 1 Time Period 3  \
Client ID                                                         
10004522518                        42                        28   
10004522519                         0                         0   
10004522520                         4                         7   
10004522521                         2                         0   
10004522522                         0                         0   

             Activity 1 Time Period 2  Activity 1 Time Period 1  \
Client ID                                                         
10004522518                        26                         2   
10004522519                         8                         2   
10004522520                         0                         0   
10004522521                         0                         0   
10004522522                         4                         0   

             Activity 1 Time Period 0  Activity 2 Time Period 11  \
Client ID                                                          
10004522518 

In [139]:

train.tail()

Company ID Client Contract Starting Month  No. of Years  \
Client ID                                                              
10004522518     6292232                            Sep             1   
10004522519     6295090                            Sep             0   
10004522520     6292206                            Sep             1   
10004522521     6292565                            Sep             1   
10004522522     6293420                            Sep             0   

             Service Category  Eligibility for Inquiries  Region Category  \
Client ID                                                                   
10004522518                 2                          1                3   
10004522519                 2                          0                8   
10004522520                 2                          0                8   
10004522521                 6                          0               14   
10004522522                 2                          0                3   

                           Industry  Activity 1 Time Period 11  \
Client ID                                                        
10004522518               Education                         50   
10004522519              Government                          0   
10004522520           Manufacturing                          0   
10004522521  Banking, Finance & Ins                          0   
10004522522               Education                          0   

             Activity 1 Time Period 10  Activity 1 Time Period 9  \
Client ID                                                          
10004522518                         32                        16   
10004522519                          0                         0   
10004522520                          4                         2   
10004522521                          0                         0   
10004522522                          4                         0   

             Activity 1 Time Period 8  Activity 1 Time Period 7  \
Client ID                                                         
10004522518                        36                        38   
10004522519                         4                         0   
10004522520                         2                         0   
10004522521                         0                         0   
10004522522                         2                         0   

             Activity 1 Time Period 6  Activity 1 Time Period 5  \
Client ID                                                         
10004522518                        42                        34   
10004522519                         2                         0   
10004522520                         3                         2   
10004522521                         0                         0   
10004522522                         0                         0   

             Activity 1 Time Period 4  Activity 1 Time Period 3  \
Client ID                                                         
10004522518                        42                        28   
10004522519                         0                         0   
10004522520                         4                         7   
10004522521                         2                         0   
10004522522                         0                         0   

             Activity 1 Time Period 2  Activity 1 Time Period 1  \
Client ID                                                         
10004522518                        26                         2   
10004522519                         8                         2   
10004522520                         0                         0   
10004522521                         0                         0   
10004522522                         4                         0   

             Activity 1 Time Period 0  Activity 2 Time Period 11  \
Client ID                                                          
10004522518 

In [140]:
train.drop(columns=['Industry', 'Client Contract Starting Month'], inplace=True)

In [141]:
#for col in train.columns:
#train.drop(columns=train.columns[5:], inplace=True)
#train = train[train.columns[2:3]]
train.drop(columns=train.columns[5:41], inplace=True)
#train.drop(columns=, inplace=True)
train.drop(columns=train.columns[17:], inplace=True)
train.columns

Index(['Company ID', 'No. of Years', 'Service Category',
       'Eligibility for Inquiries', 'Region Category',
       'Activity 4 Time Period 11', 'Activity 4 Time Period 10',
       'Activity 4 Time Period 9', 'Activity 4 Time Period 8',
       'Activity 4 Time Period 7', 'Activity 4 Time Period 6',
       'Activity 4 Time Period 5', 'Activity 4 Time Period 4',
       'Activity 4 Time Period 3', 'Activity 4 Time Period 2',
       'Activity 4 Time Period 1', 'Activity 4 Time Period 0'],
      dtype='object')

In [142]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train[:train_len], y, test_size=0.25, random_state=0)

In [143]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score, confusion_matrix
svc = SVC()
svc.fit(X_train, y_train)
y_pred_train = svc.predict(X_train)
y_pred_test = svc.predict(X_test)
print(f1_score(y_train, y_pred_train))
print(f1_score(y_test, y_pred_test))
print(confusion_matrix(y_test, y_pred_test))

0.8890184645286685
0.8067834306366416
[[  46  597]
 [  98 1451]]


In [52]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier()
classifier.fit(X_train, y_train)
y_pred_train = classifier.predict(X_train)
y_pred_test = classifier.predict(X_test)
print(f1_score(y_train, y_pred_train))
print(f1_score(y_test, y_pred_test))
print(confusion_matrix(y_test, y_pred_test))

0.8318329132157004
0.8250134192163178
[[   3  640]
 [  12 1537]]


## Removing Activity 5, 6, 7 columns & without summation columns

In [77]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score, confusion_matrix
svc = SVC()
svc.fit(X_train, y_train)
y_pred_train = svc.predict(X_train)
y_pred_test = svc.predict(X_test)
print(f1_score(y_train, y_pred_train))
print(f1_score(y_test, y_pred_test))
print(confusion_matrix(y_test, y_pred_test))

0.8813492841733673
0.7905788876276958
[[  61  582]
 [ 156 1393]]


In [78]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier()
classifier.fit(X_train, y_train)
y_pred_train = classifier.predict(X_train)
y_pred_test = classifier.predict(X_test)
print(f1_score(y_train, y_pred_train))
print(f1_score(y_test, y_pred_test))
print(confusion_matrix(y_test, y_pred_test))

0.8275985663082438
0.8256094294133405
[[   0  643]
 [   8 1541]]


In [109]:
svc = SVC()
svc.fit(X_train, y_train)
y_pred_train = svc.predict(X_train)
y_pred_test = svc.predict(X_test)
print(f1_score(y_train, y_pred_train))
print(f1_score(y_test, y_pred_test))
print(confusion_matrix(y_test, y_pred_test))

0.8255471192496651
0.8281208233092756
[[   0  643]
 [   0 1549]]


In [144]:
classifier = GradientBoostingClassifier()
classifier.fit(X_train, y_train)
y_pred_train = classifier.predict(X_train)
y_pred_test = classifier.predict(X_test)
print(f1_score(y_train, y_pred_train))
print(f1_score(y_test, y_pred_test))
print(confusion_matrix(y_test, y_pred_test))

0.8281796181769293
0.826866470430827
[[   0  643]
 [   4 1545]]


In [114]:
y_pred_test[y_pred_test == 0]

array([], dtype=int32)